### ISSUE TITLE
Model data type

### ISSUE THREAD

**Issue by ghost** [eoctet/Octet.Chat#1]
Hello, 

where can the LLM data model be found  ggml-model-7b-q6_k.gguf ?

What kind of data type is gguf ?

The only models i can find at huggingface.co/meta-llama/ are .bin or .pth files.

Thanks in advance :)

**Comment by eoctet** [comment]
@Phalanx-SoftDev 

.gguf is the quantization model file format of llama.cpp tool.

  you need to quantify the original model yourself using llama.cpp tool, or find a shared quantization model on huggingface.   
for example: https://huggingface.co/hfl/chinese-llama-2-7b-16k-gguf

**Comment by ghost** [comment]
@eoctet Thanks a lot !!
